# THIS IS THE COMPLETE, CORRECTED compose.yml TO PASTE
version: '3.8' # Use a modern Docker Compose version

services:
  hbbs:
    container_name: hbbs
    image: rustdesk/rustdesk-server:latest
    # -k _ means an empty key, replace with your actual public key (e.g., -k <YOUR_KEY_HERE>)
    # -r specifies the relay server clients should use (desk.captainkirk.dev:21117)
    command: hbbs -r desk.captainkirk.dev:21117 -k _
    volumes:
      - rustdesk_data:/root # Mounts the persistent disk to /root inside container for DB
    # REMOVED: network_mode: host (Render handles networking internally)
    ports: # EXPOSE ALL REQUIRED PORTS FOR HBBS
      - "21115:21115/tcp" # HBBS Signaling Server (main port)
      - "21118:21118/udp" # HBBS UDP for hole-punching
    restart: always
    depends_on:
      - hbbr # hbbs needs hbbr to be running for its relay part

  hbbr:
    container_name: hbbr
    image: rustdesk/rustdesk-server:latest
    command: hbbr # Relay server command
    volumes:
      - rustdesk_data:/root # Mounts the persistent disk to /root inside container for DB
    # REMOVED: network_mode: host
    ports: # EXPOSE ALL REQUIRED PORTS FOR HBBR
      - "21116:21116/tcp" # HBBR Relay Server (main port)
      - "21117:21117/tcp" # If clients connect directly to 21117 for relay (as specified by hbbs command)
      - "21119:21119/udp" # HBBR UDP
    restart: always

# Define named volumes for Docker Compose
volumes:
  rustdesk_data: {} # This volume will be mapped to Render's Persistent Disk
